version: '3.8'

services:
  staticman:
    image: staticman:latest
    environment:
      - NODE_ENV=production
      - PORT=8080
    secrets:
      - github_token
      - rsa_private_key
    networks:
      - staticman-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - staticman-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  staticman-network:
    driver: overlay
    attachable: true

configs:
  nginx_config:
    external: true

secrets:
  github_token:
    external: true
  rsa_private_key:
    external: true
