version: '3.8'

services:
  staticman:
    image: vincenttam/staticman:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - staticman
    restart: unless-stopped
