version: '3.8'

services:
  staticman:
    image: vincenttam/staticman:latest
    environment:
      - NODE_ENV=production
      - PORT=8080
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
    networks:
      - staticman-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1  # Reduced for e2-micro
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
    configs:
      - source: nginx_ssl_config
        target: /etc/nginx/nginx.conf
    volumes:
      - ssl-certs:/etc/nginx/ssl:ro
      - certbot-www:/var/www/certbot:ro
    networks:
      - staticman-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ssl-certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
    deploy:
      replicas: 0  # Only run when needed
      restart_policy:
        condition: none

networks:
  staticman-network:
    driver: overlay
    attachable: true

volumes:
  ssl-certs:
    driver: local
  certbot-www:
    driver: local

configs:
  nginx_ssl_config:
    external: true
