version: '3.8'

services:
  staticman:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=8080
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
    restart: unless-stopped
    networks:
      - staticman-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - staticman
    networks:
      - staticman-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  staticman-network:
    driver: bridge
